// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5MDLMbHdFtDPcp94BwguPKYWmp1YcM6Y',
    appId: '1:70707675373:web:c3f7c5f683464fa6128ce4',
    messagingSenderId: '70707675373',
    projectId: 'expensetracker-b8f5f',
    authDomain: 'expensetracker-b8f5f.firebaseapp.com',
    storageBucket: 'expensetracker-b8f5f.firebasestorage.app',
    measurementId: 'G-FPYLEYMQHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0YdDEoO2a4Aa1KaUXe4Rmx5KLgog-0c',
    appId: '1:70707675373:android:ec430bf16f0176bd128ce4',
    messagingSenderId: '70707675373',
    projectId: 'expensetracker-b8f5f',
    storageBucket: 'expensetracker-b8f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJaRSLrS_MFSiwJmp_yCPcIww0VNeDdg',
    appId: '1:70707675373:ios:3cb9fd425eafc9a7128ce4',
    messagingSenderId: '70707675373',
    projectId: 'expensetracker-b8f5f',
    storageBucket: 'expensetracker-b8f5f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJaRSLrS_MFSiwJmp_yCPcIww0VNeDdg',
    appId: '1:70707675373:ios:3cb9fd425eafc9a7128ce4',
    messagingSenderId: '70707675373',
    projectId: 'expensetracker-b8f5f',
    storageBucket: 'expensetracker-b8f5f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5MDLMbHdFtDPcp94BwguPKYWmp1YcM6Y',
    appId: '1:70707675373:web:164e0baa6b4ec172128ce4',
    messagingSenderId: '70707675373',
    projectId: 'expensetracker-b8f5f',
    authDomain: 'expensetracker-b8f5f.firebaseapp.com',
    storageBucket: 'expensetracker-b8f5f.firebasestorage.app',
    measurementId: 'G-C89V0WES7Y',
  );
}
